"""improved the moodboard as well as moodboardcanvas schemas

Revision ID: 09474bd35440
Revises: 30058ead124a
Create Date: 2025-10-28 04:54:42.452768

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '09474bd35440'
down_revision: Union[str, Sequence[str], None] = '30058ead124a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('moodboard', sa.Column('images', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('moodboard', sa.Column('prompt', sa.Text(), nullable=True))
    op.drop_column('moodboard', 'images_with_prompts')
    op.add_column('moodboard_canvas', sa.Column('canvas_urls', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.drop_column('moodboard_canvas', 'canvas_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('moodboard_canvas', sa.Column('canvas_url', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('moodboard_canvas', 'canvas_urls')
    op.add_column('moodboard', sa.Column('images_with_prompts', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('moodboard', 'prompt')
    op.drop_column('moodboard', 'images')
    # ### end Alembic commands ###
