"""improved the MoodBoard model and added a MoodBoardCanvas model

Revision ID: 30058ead124a
Revises: 96b2c2abde89
Create Date: 2025-10-28 04:19:08.205927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '30058ead124a'
down_revision: Union[str, Sequence[str], None] = '96b2c2abde89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('moodboard_canvas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('moodboard_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('canvas_url', sa.Text(), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('is_favorite', sa.Boolean(), nullable=False),
    sa.Column('generation_params', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['moodboard_id'], ['moodboard.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_moodboard_canvas_id'), 'moodboard_canvas', ['id'], unique=False)
    op.add_column('moodboard', sa.Column('color_palette', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('moodboard', sa.Column('images_with_prompts', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('moodboard', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('moodboard', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('moodboard', 'user_id',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('moodboard', 'brand_name',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('moodboard', 'color_palatte')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('moodboard', sa.Column('color_palatte', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.alter_column('moodboard', 'brand_name',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('moodboard', 'user_id',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_column('moodboard', 'updated_at')
    op.drop_column('moodboard', 'created_at')
    op.drop_column('moodboard', 'images_with_prompts')
    op.drop_column('moodboard', 'color_palette')
    op.drop_index(op.f('ix_moodboard_canvas_id'), table_name='moodboard_canvas')
    op.drop_table('moodboard_canvas')
    # ### end Alembic commands ###
